### ISSUE TITLE
feed 插件的功能要求

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/plugin-feed#1]
## 功能要求

1. 插件需要注册 `/feed.xml` 或者 `/rss.xml` 的路由以输出最近的文章更新。
2. 需要支持针对单个分类的订阅链接，比如 `/feed/categories/halo.xml`，即只输出 halo 分类下的文章更新。
3. 需要支持针对单个作者的订阅链接，比如 `/feed/authors/ryanwang.xml`，即只输出作者为 ryanwang 的文章更新。
4. 需要提供以下配置项：
    1. 是否开启单个分类的订阅链接。
    2. 是否开启单个作者的订阅链接。
    3. 内容输出类型：全文（即 `post.spec.content`）或者摘要（即 `post.status.excerpt`）。
    4. 内容输出条数。

**Comment by ruibaby** [comment]
RSS 规范可参考：https://validator.w3.org/feed/docs/rss2.html

**Comment by ruibaby** [comment]
> Hi @ruibaby ，这个插件在写了吗，还没有开始的话我来提PR吧

just do it！

**Comment by longjuan** [comment]
不过这个模板好像有点旧

**Comment by ruibaby** [comment]
> 不过这个模板好像有点旧

很早以前就创建这个库了，你可以用最新的 plugin-starter 来覆盖。
