### ISSUE TITLE
用nginx反带后rss订阅链接不可用

### ISSUE THREAD

**Issue by waitsaber** [halo-sigs/plugin-feed#13]
网站使用mginx反代halo后启用RSS插件后.xml里的地址全是http://127.0.0.1:8090，也就是反代前的地址，希望可以修改为反代后的地址也就是域名。
![图片](https://github.com/halo-sigs/plugin-feed/assets/67093172/dc896dbb-5eb6-45fe-8866-64c1a931d0b1)

**Comment by JohnNiang** [comment]
反向代理时，需要同时代理 `X-Forward-For` header。

**Comment by waitsaber** [comment]
解决办法就是将面板生成的反代文件夹中的`proxy_set_header Host` 参数修改成 域名

**Comment by backunderstar** [comment]
请问，我是用1panel直接装的halo，rss也出现了localhost:8080的问题，我参照上述操作，更改了反向代理配置文件的proxy_set_header Host但因为1panel中halo是在docker中，我不知怎么更改配置文件，可以帮我指明关于X-Forward-For在哪里吗，或者说配置文件一般在哪里。如有打扰，非常抱歉

**Comment by backunderstar** [comment]
已解决，打扰。

**Comment by ahui-atong** [comment]
> 已解决，打扰。
哥们，你咋解决的，我和你一样的情况

**Comment by backunderstar** [comment]
> > 已解决，打扰。
> > 哥们，你咋解决的，我和你一样的情况

如果你也是给我一样用的1panel，那么可以在安装时写好外部访问地址，如下图：
![image](https://github.com/halo-dev/plugin-feed/assets/89375248/8dafa6c2-f5e9-420e-b946-ebfcdd22c38e)
或者在应用目录下更改.env文件中的全局变量`HALO_EXTERNAL_URL`后重建应用，推荐直接备份重新装一下halo，按照上面图的位置写好外部访问地址。
我的问题是这样解决的，希望对你有帮助。如果这样操作还是有问题，那就是Nginx代理的问题了。

**Comment by KingStoning** [comment]
> > > 已解决，打扰。
> > > 哥们，你咋解决的，我和你一样的情况
> 
> 如果你也是给我一样用的1panel，那么可以在安装时写好外部访问地址，如下图： ![image](https://github.com/halo-dev/plugin-feed/assets/89375248/8dafa6c2-f5e9-420e-b946-ebfcdd22c38e) 或者在应用目录下更改.env文件中的全局变量`HALO_EXTERNAL_URL`后重建应用，推荐直接备份重新装一下halo，按照上面图的位置写好外部访问地址。 我的问题是这样解决的，希望对你有帮助。如果这样操作还是有问题，那就是Nginx代理的问题了。

感谢啊，我的问题解决了，这是最简单的方法了
