### ISSUE TITLE
什么时候发版

### ISSUE THREAD

**Issue by sun0225SUN** [halo-sigs/plugin-feed#2]
这个插件没有发版哇，现在可以正常使用么，想用😻

**Comment by ruibaby** [comment]
已经发布。

https://github.com/halo-sigs/plugin-feed/releases/tag/v1.1.0-beta.1

**Comment by sun0225SUN** [comment]
> 已经发布。
> 
> https://github.com/halo-sigs/plugin-feed/releases/tag/v1.1.0-beta.1

为啥都没有标签，生成是生成了，但好像没法用。https://blog.sunguoqi.com/feed.xml

![image](https://user-images.githubusercontent.com/79169717/216572009-a2629534-cb89-4cd7-a5df-8f7ef59c1253.png)

下图是别人的 rss，https://zylele.github.io/atom.xml
![image](https://user-images.githubusercontent.com/79169717/216572211-6a8deb62-3085-4d18-bd77-3ad10fe23d74.png)

**Comment by sun0225SUN** [comment]
@ruibaby

**Comment by JohnNiang** [comment]
![Screenshot_2023-02-03-19-03-55-367_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/16865714/216587916-c14d9e91-7e4b-4fe6-aead-b234ffbe9a24.jpg)

我这里看到的是正常的。

**Comment by sun0225SUN** [comment]
有点奇怪哇，不太理解，刚用无痕模式看到的正常，但直接打开还是没标签（已清除缓存）

![image](https://user-images.githubusercontent.com/79169717/216605301-e4f10d46-d466-44fe-abd2-b1ef8426a367.png)

**Comment by sun0225SUN** [comment]
> 尝试在插件设置里把内容输出类型调整为全文

浏览器渲染问题，可以正常使用。

一开始以为不能正常使用，后来发现是另一个程序的问题，打扰了哈，辛苦啦:heart:

![image](https://user-images.githubusercontent.com/79169717/216646625-e55e0dcc-bf92-4a39-ac00-b43602b32c91.png)
